package com.thoughtworks;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.thoughtworks.App;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertThat( classUnderTest.getGreeting()).isEqualTo("Hello world.");
    }
}
